[package]
name = "pixel_param"
version = "0.1.0"
authors = ["zhenfei <zhenfei.zhang@hotmail.com>"]
edition = "2018"


[dependencies]
#pairing-plus = {path = "../pairing-plus"}
pairing-plus = {git = "https://github.com/algorand/pairing-plus"}
#pairing-plus = "0.17"
hkdf = "0.7"
sha2 = "0.8"
