[package]
name = "pixel_param"
version = "0.1.0"
authors = ["zhenfei <zhenfei.zhang@hotmail.com>"]
edition = "2018"


[dependencies]
#pairing = { version = "0.15", git = "https://github.com/algorand/pairing-fork"}
pairing-plus = "0.17"
hkdf = "0.7"
sha2 = "0.8"
